name: Backend test

on:
  push:
    branches:
      - my-metrik-master
    paths:
      - backend/**
      - .github/actions/backend_test/**
      - .github/workflows/backend_test.yaml

  pull_request:
    branches:
      - my-metrik-master
    paths:
      - backend/**
      - .github/actions/backend_test/**
      - .github/workflows/backend_test.yaml

  workflow_dispatch:

jobs:
  backend-test:
    name: Backend module test
    runs-on: ubuntu-latest

    steps:
      - name: Setup timezone
        run: sudo timedatectl set-timezone "Asia/Shanghai"

      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-package: 'jdk'
          java-version: '11'
          check-latest: true

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run backend tests
        uses: ./.github/actions/backend_test
        with:
          working-dir: ./backend

      - name: Upload Kover coverage reports
        uses: codecov/codecov-action@v2
        with:
          files: ./backend/build/reports/kover/report.xml,./backend/build/reports/kover/html/index.html

##     This step allow you to debug via SSH
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3
#        with:
#          sudo: true
